source: DynatraceSaas-NZ. source instance: NZ Pre-Production. Application: ane-1-0

OPEN Custom Alert P-21058471 in environment NZ Pre-Production
Problem detected at: 03:25 (UTC) 21.05.2021

1 impacted infrastructure component

Host
OS_DEV - nzd2c34v.unix.anznb.co.nz

Openshift Node Memory usage
The Memory used % value of 95.33% was above your custom threshold of 95%.

https://ckk60131.live.dynatrace.com/#problems/problemdetails;pid=-1368661935545057361_1621567500000V2